# Generated by Django 3.1.3 on 2020-11-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=100)),
                ('switch_id', models.CharField(max_length=100)),
                ('state', models.IntegerField(max_length=2)),
            ],
        ),
    ]
